apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    config.k8s.io/function: |
      container:
        image:  gcr.io/kpt-functions/expand-team-cr
    config.kubernetes.io/local-config: 'true'
  labels:
    remove: 'yes'
data: {}
